#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: 381dfd8
#
Name     : R-spatstat.sparse
Version  : 3.1.0
Release  : 21
URL      : https://cran.r-project.org/src/contrib/spatstat.sparse_3.1-0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/spatstat.sparse_3.1-0.tar.gz
Summary  : Sparse Three-Dimensional Arrays and Linear Algebra Utilities
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-spatstat.sparse-lib = %{version}-%{release}
Requires: R-abind
Requires: R-spatstat.utils
Requires: R-tensor
BuildRequires : R-abind
BuildRequires : R-spatstat.utils
BuildRequires : R-tensor
BuildRequires : buildreq-R

%description
and supports standard operations on them.
	     The package also includes utility functions for
	     matrix calculations that are common in
	     statistics, such as quadratic forms.

%package lib
Summary: lib components for the R-spatstat.sparse package.
Group: Libraries

%description lib
lib components for the R-spatstat.sparse package.


%prep
%setup -q -n spatstat.sparse
pushd ..
cp -a spatstat.sparse buildavx2
popd
pushd ..
cp -a spatstat.sparse buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1718988452

%install
export SOURCE_DATE_EPOCH=1718988452
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/spatstat.sparse/CITATION
/usr/lib64/R/library/spatstat.sparse/DESCRIPTION
/usr/lib64/R/library/spatstat.sparse/INDEX
/usr/lib64/R/library/spatstat.sparse/Meta/Rd.rds
/usr/lib64/R/library/spatstat.sparse/Meta/features.rds
/usr/lib64/R/library/spatstat.sparse/Meta/hsearch.rds
/usr/lib64/R/library/spatstat.sparse/Meta/links.rds
/usr/lib64/R/library/spatstat.sparse/Meta/nsInfo.rds
/usr/lib64/R/library/spatstat.sparse/Meta/package.rds
/usr/lib64/R/library/spatstat.sparse/NAMESPACE
/usr/lib64/R/library/spatstat.sparse/NEWS
/usr/lib64/R/library/spatstat.sparse/R/spatstat.sparse
/usr/lib64/R/library/spatstat.sparse/R/spatstat.sparse.rdb
/usr/lib64/R/library/spatstat.sparse/R/spatstat.sparse.rdx
/usr/lib64/R/library/spatstat.sparse/doc/packagesizes.txt
/usr/lib64/R/library/spatstat.sparse/help/AnIndex
/usr/lib64/R/library/spatstat.sparse/help/aliases.rds
/usr/lib64/R/library/spatstat.sparse/help/macros/defns.Rd
/usr/lib64/R/library/spatstat.sparse/help/paths.rds
/usr/lib64/R/library/spatstat.sparse/help/spatstat.sparse.rdb
/usr/lib64/R/library/spatstat.sparse/help/spatstat.sparse.rdx
/usr/lib64/R/library/spatstat.sparse/html/00Index.html
/usr/lib64/R/library/spatstat.sparse/html/R.css
/usr/lib64/R/library/spatstat.sparse/info/packagesizes.txt
/usr/lib64/R/library/spatstat.sparse/tests/linalgeb.R
/usr/lib64/R/library/spatstat.sparse/tests/sparse3Darrays.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/spatstat.sparse/libs/spatstat.sparse.so
/V4/usr/lib64/R/library/spatstat.sparse/libs/spatstat.sparse.so
/usr/lib64/R/library/spatstat.sparse/libs/spatstat.sparse.so
